# **2 - Loading**

## Import Libraries

In [33]:
import psycopg2
import pandas as pd

## Connect to Database

In [34]:
connection = psycopg2.connect(
    
    host = 'localhost',
    port = '5432',
    database = 'demo',
    user = 'bryguan',
    password = 'qwertyuiop')

cursor = connection.cursor()

## Drop Existing Tables

### Customers

In [35]:
query = '''

DROP TABLE IF EXISTS customers;

'''

connection.rollback()
cursor.execute(query)
connection.commit()

### Sales

In [36]:
query = '''

DROP TABLE IF EXISTS sales;

'''

connection.rollback()
cursor.execute(query)
connection.commit()

### Stores

In [37]:
query = '''

DROP TABLE IF EXISTS stores;

'''

connection.rollback()
cursor.execute(query)
connection.commit()

### Products

In [38]:
query = '''

DROP TABLE IF EXISTS products;

'''

connection.rollback()
cursor.execute(query)
connection.commit()

## Create Staging Tables

### Customers

In [39]:
query = '''

CREATE TABLE customers (
    stage_id serial,
    sale_id char(10),
    customer_id char(7),
    first_name varchar(25),
    last_name varchar(25),
    street varchar(50),
    city varchar(25),
    state char(2),
    zip char(5)
)

'''

connection.rollback()
cursor.execute(query)
connection.commit()

### Sales

In [40]:
query = '''

CREATE TABLE sales (
    stage_id serial,
    sale_id char(10),
    sale_date char(10),
    sub_total varchar(10),
    tax varchar(10),
    total varchar(10)
)

'''

connection.rollback()
cursor.execute(query)
connection.commit()

### Stores

In [41]:
query = '''

CREATE TABLE stores (
    stage_id serial,
    sale_id char(10),
    store_id char(5),
    name varchar(25),
    street varchar(50),
    city varchar(25),
    state char(2),
    zip char(5)
)

'''

connection.rollback()
cursor.execute(query)
connection.commit()

### Products

In [42]:
query = '''

CREATE TABLE products (
    stage_id serial,
    sale_id char(10),
    item_id varchar(10),
    product_id char(10),
    price varchar(10),
    quantity varchar(10)
)

'''

connection.rollback()
cursor.execute(query)
connection.commit()

## Load

In [43]:
query = '''

COPY customers (sale_id, customer_id, first_name, last_name, street, city, state, zip)
FROM '/Users/bryguan/demo/customers.csv' DELIMITER ',' NULL '' CSV HEADER;

COPY sales (sale_id, sale_date, sub_total, tax, total)
FROM '/Users/bryguan/demo/sales.csv' DELIMITER ',' NULL '' CSV HEADER;

COPY stores (sale_id, store_id, name, street, city, state, zip)
FROM '/Users/bryguan/demo/stores.csv' DELIMITER ',' NULL '' CSV HEADER;

COPY products (sale_id, item_id, product_id, price, quantity)
FROM '/Users/bryguan/demo/products.csv' DELIMITER ',' NULL '' CSV HEADER;

'''

connection.rollback()
cursor.execute(query)
connection.commit()

## Verify Load

### Customers

In [44]:
query = '''

SELECT *
FROM customers
ORDER BY stage_id;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

,stage_id,sale_id,customer_id,first_name,last_name,street,city,state,zip
0,1,5763728874,3728404,Darrelle,Dohrmann,46 Farwell Terrace,Oakland,CA,94609
1,2,5763729036,3729309,Moria,Greenwood,8803 Delaware Crossing,Berkeley,CA,94705
2,3,5763728904,3728508,Josiah,Hulett,6755 Melby Plaza,Oakland,CA,94612
3,4,5763728973,3728534,Gayle,MacGarrity,286 Onsgard Center,Berkeley,CA,94703
4,5,5763728757,3729188,Courtenay,Shirrell,75 West Park,Emeryville,CA,94608
...,...,...,...,...,...,...,...,...,...
92,93,5763728927,3728568,Valina,Spring,119 Sachtjen Junction,Berkeley,CA,94702
93,94,5763729096,3728990,Claire,Mebes,358 Oxford Road,Albany,CA,94706
94,95,5763729268,3728901,Freddy,Mumford,6 Transport Lane,Orinda,CA,94563
95,96,5763729237,3729019,Arv,Doret,2120 Mesta Circle,Emeryville,CA,94608
96,97,5763728673,3728691,Eula,Dewair,3 Crownhardt Road,Albany,CA,94706

### Sales

In [45]:
query = '''

SELECT *
FROM sales
ORDER BY stage_id;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

    stage_id     sale_id   sale_date sub_total tax total
0          1  5763728874  2020-10-03        12   0    12
1          2  5763729036  2020-10-03        72   0    72
2          3  5763728904  2020-10-03        24   0    24
3          4  5763728973  2020-10-03        96   0    96
4          5  5763728757  2020-10-03       108   0   108
..       ...         ...         ...       ...  ..   ...
92        93  5763728927  2020-10-03        72   0    72
93        94  5763729096  2020-10-03        48   0    48
94        95  5763729268  2020-10-03        84   0    84
95        96  5763729237  2020-10-03        60   0    60
96        97  5763728673  2020-10-03        48   0    48

[97 rows x 6 columns]

### Stores

In [46]:
query = '''

SELECT *
FROM stores
ORDER BY stage_id;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

,stage_id,sale_id,store_id,name,street,city,state,zip
0,1,5763728874,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
1,2,5763729036,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
2,3,5763728904,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
3,4,5763728973,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
4,5,5763728757,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
...,...,...,...,...,...,...,...,...
92,93,5763728927,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
93,94,5763729096,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
94,95,5763729268,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
95,96,5763729237,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705
96,97,5763728673,12573,Acme Gourmet Meals,3000 Telegraph Ave,Berkeley,CA,94705

### Products

In [47]:
query = '''

SELECT *
FROM products
ORDER BY stage_id;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

     stage_id     sale_id item_id  product_id price quantity
0           1  5763728874       1  42314680      12        1
1           2  5763729036       1  42314677      12        1
2           3  5763729036       2  42314682      12        3
3           4  5763729036       3  42314684      12        2
4           5  5763728904       1  42314680      12        1
..        ...         ...     ...         ...   ...      ...
347       348  5763729237       2  42314678      12        2
348       349  5763729237       3  42314682      12        2
349       350  5763728673       1  42314677      12        2
350       351  5763728673       2  42314678      12        1
351       352  5763728673       3  42314682      12        1

[352 rows x 6 columns]

## Close Connection

In [48]:
connection.close()