# **4 - Analyzing**

## Importing Libraries

In [1]:
import psycopg2
import pandas as pd

## Connect to Database

In [2]:
connection = psycopg2.connect(
    
    host = 'localhost',
    port = '5432',
    database = 'demo',
    user = 'bryguan',
    password = 'qwertyuiop')

cursor = connection.cursor()

## Summary Statistics

### Total Sales Sum

In [3]:
query = '''

SELECT SUM(total::numeric) as total_sales_sum
FROM sales;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

   total_sales_sum
0           6480.0

### Total Sales Count

In [4]:
query = '''

SELECT COUNT(sale_id) as total_sales_count
FROM sales;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

   total_sales_count
0                 97

### Total Products Count

In [5]:
query = '''

SELECT SUM(quantity::numeric) as total_products_count
FROM products;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

   total_products_count
0                 540.0

### Total Product Count by Product

In [6]:
query = '''

SELECT product_id, SUM(quantity::numeric) as total_product_count
FROM products
GROUP BY product_id
ORDER BY total_product_count DESC;

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

   product_id  total_product_count
0  42314677                  113.0
1  42314680                  107.0
2  42314682                  101.0
3  42314678                   80.0
4  42314684                   60.0
5  42314683                   44.0
6  42314679                   27.0
7  42314681                    8.0

### Average Product Count per Sale

In [7]:
query = '''

WITH
    subquery_total_products as
    (
    SELECT SUM(quantity::numeric) as total_products
    FROM products
    ),
    subquery_total_sales as
    (
    SELECT count(*) as total_sales
    FROM sales
    )
SELECT total_products / total_sales AS average_product_count_per_sale
FROM subquery_total_products, subquery_total_sales

'''

connection.rollback()
display(pd.read_sql_query(query, connection))

   average_product_count_per_sale
0                         5.56701

## Close Connection

In [8]:
connection.close()